version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - 'backend/:/backend/'
    command: >
      sh -c 'sbt backend/run'
    environment:
      - APPLICATION_SECRET=fooo
      - JDBC_DATABASE_URL='jdbc:postgresql://localhost:5432/michel?user=michel&password=1234'
    depends_on:
      - database
  database:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=michel
      - POSTGRES_USER=michel
      - POSTGRES_PASSWORD=1234
volumes:
  postgres_data:
  backend:
    external:
      true
