name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install metaflow pandas matplotlib notebook
    - name: Check metaflows
      run: |
        cd exercise1
        python stats.py show
        python stats.py run --group country
        python stats.py run --group user_id
        cd ..

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile project
      run: |
        cd exercise2
        sbt stage
        cd ..

    # - name: Build the Docker images
    #   run: |
    #     docker build . --file Dockerfile --tag backend:latest

    # - docker-compose ...
